







export const metadata = {
  title: "Create Next Appaaaaaa",
  description: "Generated by create next app",
};



export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    {children}
    </>

  );
}
