
import type { Metadata } from "next";
import React, { useEffect } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "../components/header"
import Hotnew from "../components/hotnew";
import Body from "../components/body";
import LinhVuc from "../components/linhvuc";
import KhachHang from "../components/khachhang";
import Footer from "../components/footer";
import Leanr from "../components/learn";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const images = [
  { src: "https://www.vjp-connect.com/images/logo-company-4.png" },
  { src: "https://www.vjp-connect.com/images/logo-company-3.png" },
  { src: "https://www.vjp-connect.com/images/logo-company-5.png" },
  { src: "https://www.vjp-connect.com/images/logo-company-1.png" },
  { src: "https://www.vjp-connect.com/images/logo-company-2.png" },
  { src: "https://www.vjp-connect.com/images/logo-company-6.png" },
];


export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Leanr
           />
        <ToastContainer/>
        {/* <Header/>
        
        <Body/>
        
        <Hotnew/>
        <LinhVuc/>
        <KhachHang images={images}/>
        <Footer/> */}

      </body>
    </html>

  );
}
