







export const metadata = {
    title: "id",
    description: "Generated by create next app",
  };
  
  
  
  export default function RootLayout({
  
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <>
      {children}
      </>
  
    );
  }
  